---
- name: Jenkins
  hosts: all

  tasks:
  - name: Put SELinux in permissive mode
    selinux:
     policy: targeted
     state: permissive

  - name: Add Jenkins repository
    yum_repository:
     name: jenkins
     description: Jenkins repo
     file: jenkins
     baseurl: http://pkg.jenkins.io/redhat-stable
     enabled: yes
     gpgcheck: yes

  - name: Import a key from a url
    ansible.builtin.rpm_key:
     state: present
     key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install epel
    yum:
     name: epel-release
     state: latest

  - name: Install Java
    yum:
     name: java-11-openjdk-devel
     state: latest

  - name: Install  Jenkins
    yum:
     name: jenkins
     state: latest

#  - name: Open port 8080
#    firewalld:
#     port: 8080/tcp
#     immediate: yes
#     permanent: yes
#     state: enabled

  - name: Start service
    service:
     name: jenkins
     enabled: true
